/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/reg/reg.component';
const styles_Register:any[] = ([] as any[]);
export const RenderType_Register:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Register,
    data:{}});
export function View_Register_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),13,'div',[['id',
      'reg']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'span',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'input',
          [['ng-model','user.name'],['placeholder','Name'],['type','text']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'span',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),0,'input',[['ng-model','user.age'],
          ['placeholder','Age'],['type','number']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),1,'span',([] as any[]),(null as any),
              (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),0,'input',[['ng-model','user.profession'],['placeholder',
              'Profession'],['type','text']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),1,'div',[['id','submit-button']],(null as any),
              [[(null as any),'click']],(_v,en,$event) => {
                var ad:boolean = true;
                var _co:i1.Register = _v.component;
                if (('click' === en)) {
                  const pd_0:any = ((<any>_co.submit()) !== false);
                  ad = (pd_0 && ad);
                }
                return ad;
              },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Next'])),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],
      (null as any),(null as any));
}
export function View_Register_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'reg',([] as any[]),
      (null as any),(null as any),(null as any),View_Register_0,RenderType_Register)),
      i0.ɵdid(49152,(null as any),0,i1.Register,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const RegisterNgFactory:i0.ComponentFactory<i1.Register> = i0.ɵccf('reg',i1.Register,
    View_Register_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2F0dXMvRGVza3RvcC9EYXRhIE1pbmluZy9zcmMvYXBwL3JlZy9yZWcuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2F0dXMvRGVza3RvcC9EYXRhIE1pbmluZy9zcmMvYXBwL3JlZy9yZWcuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYXR1cy9EZXNrdG9wL0RhdGEgTWluaW5nL3NyYy9hcHAvcmVnL3JlZy5odG1sIiwibmc6Ly8vVXNlcnMvYXR1cy9EZXNrdG9wL0RhdGEgTWluaW5nL3NyYy9hcHAvcmVnL3JlZy5jb21wb25lbnQudHMuUmVnaXN0ZXJfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGlkPVwicmVnXCI+XG4gIDxzcGFuPjxpbnB1dCB0eXBlPVwidGV4dFwiIG5nLW1vZGVsPVwidXNlci5uYW1lXCIgcGxhY2Vob2xkZXI9XCJOYW1lXCI+PC9zcGFuPlxuICA8c3Bhbj48aW5wdXQgdHlwZT1cIm51bWJlclwiIG5nLW1vZGVsPVwidXNlci5hZ2VcIiBwbGFjZWhvbGRlcj1cIkFnZVwiPjwvc3Bhbj5cbiAgPHNwYW4+PGlucHV0IHR5cGU9XCJ0ZXh0XCIgbmctbW9kZWw9XCJ1c2VyLnByb2Zlc3Npb25cIiBwbGFjZWhvbGRlcj1cIlByb2Zlc3Npb25cIj48L3NwYW4+XG4gIDxkaXYgaWQ9XCJzdWJtaXQtYnV0dG9uXCIgKGNsaWNrKT1cInN1Ym1pdCgpXCI+TmV4dDwvZGl2PlxuPC9kaXY+XG4iLCI8cmVnPjwvcmVnPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBYyx5Q0FDWjtVQUFBO1VBQUEsZ0JBQU07VUFBQTtVQUFBLDBEQUFrRTtVQUFBLFdBQ3hFO1VBQUE7TUFBTTtVQUFBO1VBQUEsOEJBQWtFLHlDQUN4RTtpQkFBQTtjQUFBLDBEQUFNO1VBQUE7Y0FBQTtVQUFBLDhCQUE4RSx5Q0FDcEY7aUJBQUE7Y0FBQTtnQkFBQTtnQkFBQTtnQkFBd0I7a0JBQUE7a0JBQUE7Z0JBQUE7Z0JBQXhCO2NBQUEsZ0NBQTJDO01BQVUsdUNBQ2pEOzs7O29CQ0xOO01BQUE7YUFBQTs7OzsifQ==
