/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/reg/reg.component';
const styles_Register:any[] = ([] as any[]);
export const RenderType_Register:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Register,
    data:{}});
export function View_Register_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),10,'div',[['id',
      'reg']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'span',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵeld(0,[['sex',1]],(null as any),0,'input',[['placeholder',
          'Gender'],['type','text']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),1,'span',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵeld(0,[['age',1]],
          (null as any),0,'input',[['placeholder','Age'],['type','number']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',[['id',
          'submit-button']],(null as any),[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.Register = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.submit(i0.ɵnov(_v,3).value,i0.ɵnov(_v,6).value)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Next'])),(_l()(),
          i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],(null as any),
      (null as any));
}
export function View_Register_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'reg',([] as any[]),
      (null as any),(null as any),(null as any),View_Register_0,RenderType_Register)),
      i0.ɵdid(49152,(null as any),0,i1.Register,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const RegisterNgFactory:i0.ComponentFactory<i1.Register> = i0.ɵccf('reg',i1.Register,
    View_Register_Host_0,{},{onWordsStart:'onWordsStart'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2F0dXMvRGVza3RvcC9EYXRhIE1pbmluZy9zcmMvYXBwL3JlZy9yZWcuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2F0dXMvRGVza3RvcC9EYXRhIE1pbmluZy9zcmMvYXBwL3JlZy9yZWcuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYXR1cy9EZXNrdG9wL0RhdGEgTWluaW5nL3NyYy9hcHAvcmVnL3JlZy5odG1sIiwibmc6Ly8vVXNlcnMvYXR1cy9EZXNrdG9wL0RhdGEgTWluaW5nL3NyYy9hcHAvcmVnL3JlZy5jb21wb25lbnQudHMuUmVnaXN0ZXJfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGlkPVwicmVnXCI+XG4gIDxzcGFuPjxpbnB1dCB0eXBlPVwidGV4dFwiICAgI3NleCBwbGFjZWhvbGRlcj1cIkdlbmRlclwiPjwvc3Bhbj5cbiAgPHNwYW4+PGlucHV0IHR5cGU9XCJudW1iZXJcIiAjYWdlIHBsYWNlaG9sZGVyPVwiQWdlXCI+PC9zcGFuPlxuICA8ZGl2IGlkPVwic3VibWl0LWJ1dHRvblwiIChjbGljayk9XCJzdWJtaXQoc2V4LnZhbHVlLCBhZ2UudmFsdWUpXCI+TmV4dDwvZGl2PlxuPC9kaXY+XG4iLCI8cmVnPjwvcmVnPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBYyx5Q0FDWjtVQUFBO1VBQUEsZ0JBQU07VUFBQTtVQUFBLGdCQUFzRCx5Q0FDNUQ7VUFBQTtVQUFBLDRDQUFNO1VBQUE7VUFBQSwwREFBbUQ7VUFBQSxXQUN6RDtVQUFBO1FBQUE7UUFBQTtRQUF3QjtVQUFBO1VBQUE7UUFBQTtRQUF4QjtNQUFBLGdDQUErRCx5Q0FBVTtpQkFBQSx3QkFDckU7Ozs7b0JDSk47TUFBQTthQUFBOzs7OyJ9
