/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/init/init.component';
const styles_Init:any[] = ([] as any[]);
export const RenderType_Init:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_Init,
    data:{}});
export function View_Init_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),0,'p',[['id','name']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),6,'div',[['class','button'],['id','google-a-btn']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          0,'span',[['id','g-icon']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),1,'span',[['class','logintext'],['id','gtext']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['Sign in with Google'])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
          'button'],['id','in-a-btn']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),1,'span',[['class','logintext']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['Sign in with LinkedIn'])),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),
          i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          2,'div',[['id','or']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['or'])),(_l()(),i0.ɵted((null as any),['\n'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class','button'],['id',
          'nreg-btn']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'span',[['class','logintext']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Normal Registration'])),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],
      (null as any),(null as any));
}
export function View_Init_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'init',([] as any[]),
      (null as any),(null as any),(null as any),View_Init_0,RenderType_Init)),i0.ɵdid(49152,
      (null as any),0,i1.Init,([] as any[]),(null as any),(null as any))],(null as any),
      (null as any));
}
export const InitNgFactory:i0.ComponentFactory<i1.Init> = i0.ɵccf('init',i1.Init,View_Init_Host_0,
    {},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2F0dXMvRGVza3RvcC9EYXRhIE1pbmluZy9zcmMvYXBwL2luaXQvaW5pdC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYXR1cy9EZXNrdG9wL0RhdGEgTWluaW5nL3NyYy9hcHAvaW5pdC9pbml0LmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2F0dXMvRGVza3RvcC9EYXRhIE1pbmluZy9zcmMvYXBwL2luaXQvaW5pdC5odG1sIiwibmc6Ly8vVXNlcnMvYXR1cy9EZXNrdG9wL0RhdGEgTWluaW5nL3NyYy9hcHAvaW5pdC9pbml0LmNvbXBvbmVudC50cy5Jbml0X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG48cCBpZD1cIm5hbWVcIj48L3A+XG48ZGl2IGlkPVwiZ29vZ2xlLWEtYnRuXCIgY2xhc3M9XCJidXR0b25cIj5cbiAgPHNwYW4gaWQ9XCJnLWljb25cIj48L3NwYW4+XG4gIDxzcGFuIGlkPVwiZ3RleHRcIiBjbGFzcz1cImxvZ2ludGV4dFwiPlNpZ24gaW4gd2l0aCBHb29nbGU8L3NwYW4+XG48L2Rpdj5cbjxzY3JpcHQ+c3RhcnRBcHAoKTs8L3NjcmlwdD5cbjxkaXYgaWQ9XCJpbi1hLWJ0blwiIGNsYXNzPVwiYnV0dG9uXCI+XG4gIDxzcGFuIGNsYXNzPVwibG9naW50ZXh0XCI+U2lnbiBpbiB3aXRoIExpbmtlZEluPC9zcGFuPlxuPC9kaXY+XG48ZGl2IGlkPVwib3JcIj48cD5vcjwvcD48L2Rpdj5cbjxkaXYgaWQ9XCJucmVnLWJ0blwiIGNsYXNzPVwiYnV0dG9uXCI+XG4gIDxzcGFuIGNsYXNzPVwibG9naW50ZXh0XCIgPk5vcm1hbCBSZWdpc3RyYXRpb248L3NwYW4+XG48L2Rpdj5cbiIsIjxpbml0PjwvaW5pdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQSx1Q0FDQTtNQUFBO01BQUEsOEJBQWlCLHVDQUNqQjthQUFBO1VBQUE7TUFBc0MseUNBQ3BDO1VBQUE7VUFBQSxnQkFBeUIseUNBQ3pCO1VBQUE7VUFBQTtNQUFtQyx3REFBMEI7VUFBQSxTQUN6RCx1Q0FDc0I7VUFBQSxTQUM1QjtVQUFBO1VBQUEsZ0JBQWtDLHlDQUNoQztVQUFBO1VBQUEsMERBQXdCO1VBQUEsNEJBQTRCLHVDQUNoRDtpQkFBQSx3QkFDTjtVQUFBO1VBQUEsZ0JBQWE7VUFBQTtNQUFHLHVDQUFZO01BQzVCO1VBQUE7TUFBa0MseUNBQ2hDO1VBQUE7VUFBQSw4QkFBeUI7TUFBMEIsdUNBQy9DOzs7O29CQ2JOO01BQUEsK0VBQUE7TUFBQTs7OzsifQ==
