/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.component';
import * as i2 from './init/init.component.ngfactory';
import * as i3 from '../../../src/app/init/init.component';
import * as i4 from './reg/reg.component.ngfactory';
import * as i5 from '../../../src/app/reg/reg.component';
import * as i6 from './words/words.component.ngfactory';
import * as i7 from '../../../src/app/words/words.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',[['id','title']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),[' ',' '])),(_l()(),i0.ɵted((null as any),['\n               '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'init',([] as any[]),[[8,'hidden',
          0]],[[(null as any),'onRegStart']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.AppComponent = _v.component;
        if (('onRegStart' === en)) {
          const pd_0:any = ((<any>_co.onRegStart()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },i2.View_Init_0,i2.RenderType_Init)),i0.ɵdid(49152,(null as any),0,i3.Init,
          ([] as any[]),(null as any),{onRegStart:'onRegStart'}),(_l()(),i0.ɵted((null as any),
          ['\n               '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,
          'reg',([] as any[]),[[8,'hidden',0]],[[(null as any),'onWordsStart']],(_v,
              en,$event) => {
            var ad:boolean = true;
            var _co:i1.AppComponent = _v.component;
            if (('onWordsStart' === en)) {
              const pd_0:any = ((<any>_co.onWordsStart($event)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },i4.View_Register_0,i4.RenderType_Register)),i0.ɵdid(49152,(null as any),
          0,i5.Register,([] as any[]),(null as any),{onWordsStart:'onWordsStart'}),
      (_l()(),i0.ɵted((null as any),['\n               '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'words',([] as any[]),[[8,'hidden',0]],[[(null as any),'onWordsDone']],
          (_v,en,$event) => {
            var ad:boolean = true;
            var _co:i1.AppComponent = _v.component;
            if (('onWordsDone' === en)) {
              const pd_0:any = ((<any>_co.onWordsDone($event)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },i6.View_Words_0,i6.RenderType_Words)),i0.ɵdid(49152,(null as any),0,i7.Words,
          ([] as any[]),(null as any),{onWordsDone:'onWordsDone'}),(_l()(),i0.ɵted((null as any),
          ['\n                ']))],(null as any),(_ck,_v) => {
    var _co:i1.AppComponent = _v.component;
    const currVal_0:any = _co.title;
    _ck(_v,1,0,currVal_0);
    const currVal_1:boolean = !_co.initOpen;
    _ck(_v,3,0,currVal_1);
    const currVal_2:boolean = !_co.regOpen;
    _ck(_v,6,0,currVal_2);
    const currVal_3:boolean = !_co.wordsOpen;
    _ck(_v,9,0,currVal_3);
  });
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(49152,(null as any),0,i1.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i1.AppComponent> = i0.ɵccf('app-root',
    i1.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2F0dXMvRGVza3RvcC9EYXRhIE1pbmluZy9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYXR1cy9EZXNrdG9wL0RhdGEgTWluaW5nL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2F0dXMvRGVza3RvcC9EYXRhIE1pbmluZy9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9hdHVzL0Rlc2t0b3AvRGF0YSBNaW5pbmcvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMSBpZD1cInRpdGxlXCI+IHt7dGl0bGV9fSA8L2gxPlxuICAgICAgICAgICAgICAgPGluaXQgIFtoaWRkZW5dPVwiIWluaXRPcGVuXCIgIChvblJlZ1N0YXJ0KSAgID0gXCJvblJlZ1N0YXJ0KClcIj48L2luaXQ+XG4gICAgICAgICAgICAgICA8cmVnICAgW2hpZGRlbl09XCIhcmVnT3BlblwiICAgKG9uV29yZHNTdGFydCkgPSBcIm9uV29yZHNTdGFydCgkZXZlbnQpXCI+PC9yZWc+XG4gICAgICAgICAgICAgICA8d29yZHMgW2hpZGRlbl09XCIhd29yZHNPcGVuXCIgKG9uV29yZHNEb25lKSAgPSBcIm9uV29yZHNEb25lKCRldmVudClcIj48L3dvcmRzPlxuICAgICAgICAgICAgICAgICIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQWU7YUFBQSwyQkFBZ0I7TUFDaEI7VUFBQTtRQUFBO1FBQUE7UUFBNkI7VUFBQTtVQUFBO1FBQUE7UUFBN0I7TUFBQSw2Q0FBQTtVQUFBLHVEQUFvRTtVQUFBLHdCQUNwRTtVQUFBO3VCQUFBO1lBQUE7WUFBQTtZQUE2QjtjQUFBO2NBQUE7WUFBQTtZQUE3QjtVQUFBLHFEQUFBO1VBQUE7TUFBMkUsc0RBQzNFO1VBQUE7VUFBQTtZQUFBO1lBQUE7WUFBNkI7Y0FBQTtjQUFBO1lBQUE7WUFBN0I7VUFBQSwrQ0FBQTtVQUFBLHlEQUE0RTtVQUFBOztJQUg1RTtJQUFBO0lBQ087SUFBUCxXQUFPLFNBQVA7SUFDTztJQUFQLFdBQU8sU0FBUDtJQUNPO0lBQVAsV0FBTyxTQUFQOzs7O29CQ0hmO01BQUE7YUFBQTs7OzsifQ==
